pipeline {
    agent any

    environment {
        OPENSHIFT_PROJECT = 'indraandriansyah-dev'  // Ganti dengan nama project OpenShift Anda
        APP_NAME = 'my-nextjs-app'  // Nama aplikasi yang Anda inginkan di OpenShift
        TOKEN_CREDS_ID = '5e05a171-1bbd-456e-9ac5-61bf0c4e1e5d' // token creds id oc
        GITHUB_REPO = 'https://github.com/IndraAndriansyah/learning-deployment-using-jenkins-in-server.git'  // Ganti dengan URL repository Anda
        OPENSHIFT_YAML = 'my-app/deployment-service-hpa.yaml'  // Ganti dengan lokasi file YAML Anda
    }

    stages {
      // HAPUS ini jika tidak dibutuhkan
        stage('Checkout Code github') {
            steps {
                git branch: 'main', url: "${GITHUB_REPO}"
            }
        }


        stage('Deploy to OpenShift') {
            steps {
                script {
                    // Login ke OpenShift
                    withCredentials([string(credentialsId: TOKEN_CREDS_ID, variable: 'OC_TOKEN')]) {
                        sh '''
                            oc login --token=$OC_TOKEN --server=https://api.rm1.0a51.p1.openshiftapps.com:6443
                        '''
                    }

                    // Pilih project OpenShift
                    sh "oc project ${OPENSHIFT_PROJECT}"

                    // Buat build dan deploy aplikasi menggunakan perintah oc new-build
                    sh '''
                        oc new-build --name=${APP_NAME} --binary --strategy=docker || echo "Build already exists"
                        oc start-build ${APP_NAME} --from-dir=my-app --follow
                        oc get is


                    '''

                         // Terapkan file YAML ke OpenShift (misalnya deployment, service, route)
                    sh "oc apply -f ${OPENSHIFT_YAML}"
                }
            }
        }
    }

    post {
        success {
            echo 'Build and deploy succeeded!'
        }
        failure {
            echo 'Build or deploy failed.'
        }
    }
}
