pipeline {
    agent any

    environment {
        OPENSHIFT_PROJECT = 'indraandriansyah-dev'  // Ganti dengan nama project OpenShift Anda
        APP_NAME = 'my-nextjs-app'  // Nama aplikasi yang Anda inginkan di OpenShift
        TOKEN_CREDS_ID = '5e05a171-1bbd-456e-9ac5-61bf0c4e1e5d' // token creds id oc
        GITHUB_REPO = 'https://github.com/IndraAndriansyah/learning-deployment-using-jenkins-in-server.git'  // Ganti dengan URL repository Anda
        OPENSHIFT_YAML = 'my-app/deployment-service-hpa.yaml'  // Ganti dengan lokasi file YAML Anda
    }

    stages {
      // HAPUS ini jika tidak dibutuhkan
        stage('Checkout Code github') {
            steps {
                git branch: 'main', url: "${GITHUB_REPO}"
            }
        }


        stage('Deploy to OpenShift') {
            steps {
               script {
                // Build dulu
                sh '''
                    oc new-build --name=${APP_NAME} --binary --strategy=docker || echo "Build already exists"
                    oc start-build ${APP_NAME} --from-dir=. --follow
                '''

                // Ambil nama image stream dari build
                def imageUrl = sh(
                    script: "oc get is ${APP_NAME} -o jsonpath='{.status.dockerImageRepository}'",
                    returnStdout: true
                ).trim()

                echo "Image URL: ${imageUrl}"

                // Ganti image di YAML secara dinamis (opsional, atau pakai template)
                writeFile file: 'my-app/deployment-service-hpa-patched.yaml',
                          text: new File('my-app/deployment-service-hpa.yaml')
                              .text
                              .replaceAll("image: .*", "image: ${imageUrl}:latest")

                // Apply yaml baru
                sh "oc apply -f my-app/deployment-service-hpa-patched.yaml"
                }

        }
    }

    post {
        success {
            echo 'Build and deploy succeeded!'
        }
        failure {
            echo 'Build or deploy failed.'
        }
    }
}
